---
- name: Ansible-fos-command module
  hosts: switches
  gather_facts: False
 
  tasks:
 
    - name: change admin and user default password
      brocade_initial_pw_setup:
        switch_address: "{{fos_ip_addr}}"
        new_admin_password: Password1
        new_user_password: Password1
      register: configout
 
    - name: print results
      debug:
        var: configout

    - name: enable root command
      brocade_fos_command:
        switch_login: admin
        switch_password: Password1
        switch_address: "{{fos_ip_addr}}"
        command_set:
          - command: userconfig --change root -e yes
          - command: rootaccess --set all
            prompts:
            - question: Please confirm to proceed
              response: "yes"
      register: configout

    - name: print results
      debug:
        var: configout

    - name: change root default password
      brocade_initial_pw_setup:
        switch_address: "{{fos_ip_addr}}"
        new_root_password: Password1
        root_only: True
 
      register: configout
 
    - name: print results
      debug:
        var: configout

...
